### ISSUE TITLE
大佬求助

### ISSUE THREAD

**Issue by mirsygo** [xireiki/tutorial-mystery#1]
![1](https://github.com/xireiki/tutorial-mystery/assets/143806353/b4d56555-eaa4-4b31-99ec-da06e7573580)
![2](https://github.com/xireiki/tutorial-mystery/assets/143806353/d5c157b0-9142-49d4-bb68-7509de0b5a6f)
请教一下，这个报错是什么问题

**Comment by bigbluebaby1** [comment]
请仔细阅读  神秘模块详细教程
